const {chromium}=require('playwright'), assert=require('node:assert/strict'), fs=require('fs'), path=require('path'), crypto=require('crypto');
(async()=>{
 const browser=await chromium.launch({headless:true}); const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}); const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.STORE_URL||'http://127.0.0.1:8877/preview/';const shots=process.env.STORE_SHOTS_DIR||path.join(__dirname,'../验收截图/应用商店');fs.mkdirSync(shots,{recursive:true});
 await page.goto(base+'#/');await page.locator('.topic').first().waitFor();assert.ok(await page.locator('.app-row').count()>12);const resources=await page.evaluate(()=>performance.getEntriesByType('resource').map(r=>({url:r.name,bytes:r.decodedBodySize})));assert.ok(!resources.some(r=>/data\/pkg|data\/search/.test(r.url)),'Homepage must not fetch details or full search');const initial=resources.reduce((n,r)=>n+r.bytes,0)+await page.evaluate(()=>performance.getEntriesByType('navigation')[0].decodedBodySize);assert.ok(initial<3000000,initial);
 for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:1000});for(const [name,route,selector] of [['首页','#/','.topic'],['分类','#/c/'+encodeURIComponent('财务与投资'),'.category-hero'],['详情','#/p/193','.product-head'],['搜索','#/s?q='+encodeURIComponent('对账'),'.best-match'],['原文','#/p/193/file/'+encodeURIComponent('skills/convert-statement/SKILL.md'),'.markdown h1'],['指南','#/guide','.guide-hero']]){await page.goto(base+route);await page.locator(selector).first().waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false, name+' overflow '+width);await page.screenshot({path:path.join(shots,name+'-'+width+'.png'),fullPage:true});if(name==='首页'&&width===1440)await page.screenshot({path:path.join(shots,'首页预览.png')});}}
 await page.goto(base+'?package=193');await page.locator('.product-head').waitFor();const [download]=await Promise.all([page.waitForEvent('download'),page.locator('[data-zip]').first().click()]);const bytes=fs.readFileSync(await download.path());const detail=JSON.parse(fs.readFileSync(path.join(process.env.STORE_DATA_DIR||path.join(__dirname,'../preview/data'),'pkg/193.json')));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),detail.asset_sha256);
 await page.goto(base+'?package=193&file='+encodeURIComponent('skills/convert-statement/SKILL.md')+'&view=reader');await page.locator('.markdown h1').waitFor();await page.locator('[data-mode="source"]').click();assert.match(await page.locator('#sourceText').textContent(),/name: convert-statement/);
 await page.goto(base+'#/p/193/file/icon.svg');await page.waitForFunction(()=>document.getElementById('readerStatus')?.textContent.includes('仅以纯文本'));assert.equal(await page.locator('#sourceText').isVisible(),true);assert.equal(await page.locator('#formattedText svg').count(),0);const unsafe=await page.evaluate(()=>sanitizeMarkdown('<script>alert(1)</script><img src=x onerror=alert(1)><a href=javascript:alert(1) onclick=alert(1)>x</a>'));assert.ok(!/script|onerror|onclick|javascript:/.test(unsafe));
 await page.goto(base+'#/c/'+encodeURIComponent('财务与投资'));await page.locator('#mcpFilter').waitFor();await page.locator('#mcpFilter').check();await page.waitForFunction(()=>location.hash.includes('mcp=1')&&document.getElementById('mcpFilter')?.checked&&[...document.querySelectorAll('.app-row small')].every(e=>e.textContent.includes('含服务连接')));assert.ok((await page.locator('.app-row small').allTextContents()).every(t=>t.includes('含服务连接')));await page.locator('#sort').selectOption('name');await page.waitForFunction(()=>location.hash.includes('sort=name'));
 await page.goto(base+'#/');await page.locator('.topic').first().waitFor();await page.evaluate(()=>window.postMessage({type:'streamlit:render',args:{package:193,file:'skills/convert-statement/SKILL.md',view:'reader'}},'*'));await page.locator('.markdown h1').waitFor();
 await page.goto(base+'#/s?q=xxzznoresult777');await page.locator('.empty').waitFor();assert.equal(await page.locator('.empty .pill').count(),5);
 assert.deepEqual(errors,[]);console.log('PASS: routes, 12 screenshots, mobile overflow, query links, original ZIP SHA, safe markdown/source, empty search; initial bytes='+initial);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
