'use strict';
const DATA=JSON.parse(document.getElementById('data').textContent),R=DATA.records,S=DATA.stats,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const DOMAIN_ORDER=['财务与投资','数据、数据库与BI','文档、知识与办公','销售、营销与电商','产品、设计与创作','AI与智能体','软件开发与测试','云平台、运维与安全','行业、研究与生活','其他与待确认'];
const SYMBOLS=['◎','▤','▧','↗','◈','✳','⌘','◇','⊙','⋯'];
let cat='',scene='',task='',page=0,current=[],selected=null,tab='overview';const PAGE=24;
const taxKey=t=>t.join(' / '), has=(r,c=cat,s=scene,t=task)=>r.taxons.some(x=>(!c||x[0]===c)&&(!s||x[1]===s)&&(!t||x[2]===t));
const countTax=(c,s='',t='')=>R.filter(r=>has(r,c,s,t)).length;
function title(r){return r.plugins.find(p=>p.displayName)?.displayName||r.file.replace(/\.zip$/i,'').replace(/ \(\d+\)$/,'').replace(/-(?:\d[\w.]*-)?v\d+$/i,'').replace(/_/g,' ')}
R.forEach(r=>{r._title=title(r);r._search=[r.file,r.summary_zh,...r.taxons.flat(),r.description,...r.skills.map(s=>[s.name,s.description,s.name_hint].join(' ')),...r.commands.map(s=>s.name+' '+s.description),...r.paths].join(' ').toLowerCase()});
$('total').textContent=S.total.toLocaleString();$('skillCount').textContent=S.skills.toLocaleString();$('taskCount').textContent=new Set(R.flatMap(r=>r.taxons.map(taxKey))).size;$('readCount').textContent=S.read.toLocaleString();
function tree(){
 $('tree').innerHTML=`<button class="nav-cat ${!cat?'active':''}" data-cat=""><span class="nav-symbol">▦</span>全部收藏<span class="nav-count">${R.length}</span></button>`+DOMAIN_ORDER.filter(c=>countTax(c)).map((c,i)=>`<div><button class="nav-cat ${cat===c?'active':''}" data-cat="${esc(c)}"><span class="nav-symbol">${SYMBOLS[i]}</span>${esc(c)}<span class="nav-count">${countTax(c)}</span></button>${cat===c?`<div class="scene-list">${[...new Set(R.flatMap(r=>r.taxons.filter(t=>t[0]===c).map(t=>t[1])))].map(s=>`<button class="nav-scene ${scene===s?'active':''}" data-scene="${esc(s)}">${esc(s)}<small>${countTax(c,s)}</small></button>`).join('')}</div>`:''}</div>`).join('');
 $('tree').querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;scene='';task='';updateNavigation();render()});
 $('tree').querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{scene=b.dataset.scene;task='';updateNavigation();render()});
}
function updateNavigation(){
 tree(); const scenes=[...new Set(R.flatMap(r=>r.taxons.filter(t=>!cat||t[0]===cat).map(t=>t[1])))].sort();
 $('scene').innerHTML='<option value="">全部工作场景</option>'+scenes.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');$('scene').value=scene;
 const tasks=[...new Set(R.flatMap(r=>r.taxons.filter(t=>(!cat||t[0]===cat)&&(!scene||t[1]===scene)).map(t=>t[2])))].sort();
 $('task').innerHTML='<option value="">全部具体任务</option>'+tasks.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');$('task').value=task;
}
function activeFilters(){
 const chips=[];if(cat)chips.push(['cat',cat]);if(scene)chips.push(['scene',scene]);if(task)chips.push(['task',task]);if($('query').value)chips.push(['query','搜索：'+$('query').value]);if($('status').value!=='all')chips.push(['status',$('status').selectedOptions[0].textContent]);if($('type').value!=='all')chips.push(['type',$('type').selectedOptions[0].textContent]);
 $('activeFilters').innerHTML=chips.map(([k,v])=>`<button class="active-chip" data-clear="${k}">${esc(v)} ×</button>`).join('')+(chips.length?'<button class="clear-filters" id="clearFilters">清空全部筛选</button>':'');
 $('activeFilters').querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{switch(b.dataset.clear){case'cat':cat='';scene='';task='';break;case'scene':scene='';task='';break;case'task':task='';break;case'query':$('query').value='';break;default:$(b.dataset.clear).value='all'}updateNavigation();render()});
 if($('clearFilters'))$('clearFilters').onclick=resetAll;
}
function shelf(){
 if(!cat&&!scene){$('taskShelf').innerHTML='';return}
 const tally=new Map();R.filter(r=>has(r,cat,scene,'')).forEach(r=>new Set(r.taxons.filter(t=>(!cat||t[0]===cat)&&(!scene||t[1]===scene)).map(t=>t[2])).forEach(t=>tally.set(t,(tally.get(t)||0)+1)));
 const ts=[...tally.entries()].sort((a,b)=>b[1]-a[1]);let visible=ts.slice(0,12);if(task&&!visible.some(t=>t[0]===task))visible.push([task,tally.get(task)||0]);
 $('taskShelf').innerHTML=visible.map(([t,n])=>`<button data-task="${esc(t)}" class="${t===task?'active':''}">${esc(t)}<small>${n}</small></button>`).join('')+(ts.length>12?'<span class="small">更多任务可从上方下拉框选择</span>':'');
 $('taskShelf').querySelectorAll('button').forEach(b=>b.onclick=()=>{task=b.dataset.task;updateNavigation();render()});
}
function saveState(){const p=new URLSearchParams();for(const[k,v]of Object.entries({cat,scene,task,q:$('query').value,status:$('status').value,type:$('type').value})){if(v&&v!=='all')p.set(k,v)}try{history.replaceState(null,'',location.pathname+location.search+(p.size?'#'+p.toString():''))}catch{}}
function render(reset=true){
 if(reset)page=0; const words=$('query').value.trim().toLowerCase().split(/\s+/).filter(Boolean),status=$('status').value,type=$('type').value;
 current=R.filter(r=>has(r)&&words.every(w=>r._search.includes(w))&&(status==='all'||(status==='read'?r.status==='已读取':r.status!=='已读取'))&&(type==='all'||(type==='skills'?r.skills.length:type==='mcp'?r.mcp_servers.length:r.duplicates?.length)));
 const pages=Math.max(1,Math.ceil(current.length/PAGE));page=Math.min(page,pages-1);
 $('heading').textContent=task||scene||cat||'探索你的工具书架';$('breadcrumb').textContent=['全部收藏',cat,scene,task].filter(Boolean).join(' / ');$('count').textContent=`${current.length.toLocaleString()} 个相关包`;$('page').textContent=`${page+1} / ${pages}`;$('prev').disabled=page===0;$('next').disabled=page>=pages-1;$('clearQuery').hidden=!$('query').value;
 $('coverage').innerHTML=`<span class="dot"></span>已读取 ${S.read.toLocaleString()} 个包的内部说明${S.pending?` · <button id="showPending">${S.pending} 个内容待读取 ↗</button>`:''} · 分类按资料推定，功能未运行验收`;
 if($('showPending'))$('showPending').onclick=()=>{cat='';scene='';task='';$('query').value='';$('type').value='all';$('status').value='pending';updateNavigation();render()};activeFilters();shelf();
 $('results').innerHTML=current.slice(page*PAGE,(page+1)*PAGE).map(r=>{
  const labels=r.taxons.filter(t=>(!cat||t[0]===cat)&&(!scene||t[1]===scene)).slice(0,3);const pending=r.status!=='已读取';
  return `<article class="card" id="item-${r.id}"><div class="card-top"><div class="avatar" aria-hidden="true">${esc(r._title[0].toUpperCase())}</div><div class="card-title"><h3>${esc(r._title)}</h3><div class="product-scene">${esc(r.category)} / ${esc(r.scene)}</div></div><span class="serial">${String(r.id).padStart(4,'0')}</span></div><p class="summary">${esc(r.summary_zh)}</p><div class="task-tags">${labels.map(t=>`<button data-tax="${esc(JSON.stringify(t))}" title="筛选此任务">${esc(t[2])}</button>`).join('')}</div><div class="card-foot"><div class="card-meta">${pending?'<span class="pending">● 内容待下载</span>':`<span>${r.skills.length} 条技能</span><span>${r.mcp_servers.length?'含服务连接':r.commands.length?r.commands.length+' 条命令':r.paths.length+' 个文件'}</span>`}${r.duplicates?.length?'<span>同内容副本</span>':''}</div><button class="open-detail" data-open="${r.id}" aria-label="查看 ${esc(r._title)} 详情">查看详情 ↗</button></div></article>`
 }).join('')||'<div id="empty"><h3>暂时没有找到合适的包</h3><p>试试更短的关键词，或清空部分筛选条件。</p><button id="emptyReset">重置筛选</button></div>';
 $('results').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDetail(Number(b.dataset.open)));
 $('results').querySelectorAll('[data-tax]').forEach(b=>b.onclick=()=>{[cat,scene,task]=JSON.parse(b.dataset.tax);updateNavigation();render()});if($('emptyReset'))$('emptyReset').onclick=resetAll;saveState();
}
function link(url,label){try{const u=new URL(String(url));return ['http:','https:'].includes(u.protocol)?`<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:esc(url)}catch{return esc(url)}}
function overview(r){return `<h3>这个包能帮你做什么</h3><p>${esc(r.summary_zh)}</p><div class="detail-badges">${r.taxons.map(t=>`<span>${esc(t.join(' / '))}</span>`).join('')}</div><p class="notice">${esc(r.evidence_note)} ${esc(r.classification_basis)}</p><h3>使用条件</h3><ul>${r.requirements.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>内容与适配线索</h3><p>${esc(r.form)} · ${esc(r.platforms.join('、')||'适配平台未识别或待确认')}</p><p>${r.paths.length} 个文件 / ${r.skills.length} 条技能 / ${r.commands.length} 条命令</p>${r.description?`<h3>包内功能说明</h3><div class="source">${esc(r.description)}</div>`:''}${r.plugins.length?`<h3>版本与来源</h3>${r.plugins.map(p=>`<p><b>${esc(p.displayName||p.name)}</b> · 版本 ${esc(p.version||'未声明')} · 许可 ${esc(p.license||'未声明')}<br><code>${esc(p.path)}</code>${p.repository?' · '+link(p.repository,'仓库'):''}${p.homepage?' · '+link(p.homepage,'主页'):''}</p>`).join('')}`:''}${r.duplicates?.length?`<h3>内容完全相同的副本</h3><p>${r.duplicates.map(esc).join('<br>')}</p>`:''}${r.same_name?.length?`<h3>同名产品的其他文件</h3><p>${r.same_name.map(esc).join('<br>')}</p><p class="small">按名称关联，内容未必相同；只有 SHA-256 相同才确认内容相同。</p>`:''}`}
function skillDetail(r){return `<h3>全部技能 · ${r.skills.length} 条</h3><p class="small">保留包内原始用途说明；名称词语提示供导航，并非全文翻译。</p>${r.skills.map(s=>`<div class="skill"><b>${esc(s.name)}</b><p class="small">${esc(s.name_hint)}</p><p>${esc(s.description||'未声明 description；主要章节：'+s.headings.join(' / '))}</p><code>${esc(s.path)}</code>${s.excerpt?`<details><summary>技能正文摘录</summary><div class="source">${esc(s.excerpt)}</div></details>`:''}</div>`).join('')||`<p>${r.status==='已读取'?'未发现 SKILL.md。':'包内内容尚未读取。'}</p>`}<h3>全部命令 · ${r.commands.length} 条</h3>${r.commands.map(s=>`<div class="skill"><b>${esc(s.name)}</b><p>${esc(s.description||s.headings.join(' / '))}</p><code>${esc(s.path)}</code></div>`).join('')||'<p>未识别到命令说明。</p>'}`}
function fileDetail(r){return `<h3>原始压缩包</h3><p>${esc(r.file)}</p><p>${(r.bytes/1024).toFixed(1)} KB · ${esc(r.status)}</p><h3>包内内容统计</h3><p>${Object.entries(r.counts).map(([k,v])=>esc(k)+' '+v).join(' · ')}</p>${r.readmes.length?`<h3>README 原文摘录</h3>${r.readmes.map(m=>`<details><summary>${esc(m.path)}</summary><div class="source">${esc(m.text)}</div></details>`).join('')}`:''}<h3>全部包内文件 · ${r.paths.length} 个</h3><pre class="filetree">${esc(r.paths.length?r.paths.join('\n'):'内容尚未读取，文件清单待确认。')}</pre>${r.sha256?`<p class="small">SHA-256：${esc(r.sha256)}</p>`:''}`}
function detailTab(){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab));$('detailBody').innerHTML=tab==='guide'?guideOverview(selected):tab==='overview'?overview(selected):tab==='skills'?skillDetail(selected):fileDetail(selected);$('detailDialog').scrollTop=0}
function openDetail(id){selected=R.find(r=>r.id===id);tab='guide';$('detailTitle').textContent=selected._title;$('detailEyebrow').textContent=selected.category+' / '+selected.scene;$('detailMeta').textContent=selected.skills.length+' 条技能 · '+selected.paths.length+' 个文件 · '+selected.status;detailTab();$('detailDialog').showModal()}
function resetAll(){cat='';scene='';task='';$('query').value='';$('status').value='all';$('type').value='all';updateNavigation();render()}
document.querySelector('.brand').onclick=e=>{e.preventDefault();resetAll();$('pageScroll').scrollTo({top:0,behavior:'smooth'})};
$('scene').onchange=()=>{scene=$('scene').value;task='';updateNavigation();render()};$('task').onchange=()=>{task=$('task').value;render()};$('status').onchange=()=>render();$('type').onchange=()=>render();let timer;$('query').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>render(),120)};$('clearQuery').onclick=()=>{$('query').value='';render();$('query').focus()};$('resetNav').onclick=()=>{cat='';scene='';task='';updateNavigation();render()};$('prev').onclick=()=>{page--;render(false);$('main').scrollIntoView({behavior:'smooth',block:'start'})};$('next').onclick=()=>{page++;render(false);$('main').scrollIntoView({behavior:'smooth',block:'start'})};$('closeDialog').onclick=()=>$('detailDialog').close();$('detailDialog').onclick=e=>{if(e.target===$('detailDialog')){const b=$('detailDialog').getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)$('detailDialog').close()}};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;detailTab()});
$('about').onclick=()=>{selected=null;$('detailTitle').textContent='第一次怎么使用技能书架';$('detailEyebrow').textContent='HOW IT WORKS / 整理依据';$('detailMeta').textContent='2026年10月7日更新';$('detailBody').innerHTML=`<h3>先搞懂：技能不是点击就运行的软件</h3><p>SKILL.md 是一份给 AI 助手看的操作说明；插件包还可能包含服务连接、脚本和参考资料。这个网站负责帮你选工具、看懂用途、下载资料。要完成任务，需要在兼容的 AI 工具里加载它。</p><h3>五步开始</h3><ol><li>按你想完成的工作搜索，例如“银行流水”“Excel”“文档整理”。</li><li>打开详情，先看“中文使用指南”：确认用途、准备材料和使用环境。</li><li>到“技能与命令”选择具体技能，点击“中文怎么用”看对应导读。</li><li>下载完整包，按原说明在兼容的 AI 工具里加载；如涉及外部服务，完成账号与连接配置。</li><li>复制指南中的中文问法，替换方括号，用小样本检查结果。原始文件随时可独立阅读全文。</li></ol><h3>从任务出发找工具</h3><p>分类按“领域 → 场景 → 具体任务”组织。同一个包可以匹配多个任务，因此分类数量会有重叠，不应相加作为包总数。优先使用产品名、包内说明和技能用途匹配；分类可能存在偏差，原始资料提供判断依据。</p><h3>当前覆盖范围</h3><p>${S.total} 个包全部建档；${S.read} 个已读取内容；${S.pending} 个待下载。${S.skills} 条技能和 ${S.commands} 条命令。</p><h3>使用前需要知道</h3><p>这里只做静态内容整理，未安装或执行任何压缩包中的程序。服务连接、账号及适配平台都是从资料识别的线索。中文用途用于导航，原文用于确认具体范围。</p><h3>下载完整资料</h3><p><a href="详细目录.md">完整文字目录</a> · <a href="目录总表.csv">目录总表</a> · <a href="技能明细.csv">技能明细</a> · <a href="分类目录.csv">三级分类表</a> · <a href="待读取清单.csv">待读取清单</a></p>`;document.querySelector('.detail-tabs').hidden=true;$('detailDialog').showModal()};$('detailDialog').addEventListener('close',()=>{document.querySelector('.detail-tabs').hidden=false});
try{const p=new URLSearchParams(location.hash.slice(1));cat=p.get('cat')||'';scene=p.get('scene')||'';task=p.get('task')||'';$('query').value=p.get('q')||'';for(const k of ['status','type'])if([...$(k).options].some(o=>o.value===p.get(k)))$(k).value=p.get(k)}catch{}updateNavigation();render();
