// Read archive files as data; never execute their contents.
const zipCache=new Map();let viewBytes=null,viewRecord=null,viewFile='',viewText='',readerFormat='formatted',viewVersion=0;
const TEXT_EXT=/\.(md|txt|json|jsonl|csv|tsv|yaml|yml|toml|ini|cfg|conf|py|js|jsx|ts|tsx|html|css|sql|sh|bash|zsh|xml|svg|rst|log|go|rs|java|c|h|cpp|r|rb|ps1|ipynb|env)$/i;
async function zipBytes(r){
 if(!r.asset_url)throw Error('此原包暂不可下载。');
 if(zipCache.has(r.asset_sha256))return zipCache.get(r.asset_sha256);
 const response=await fetch(r.asset_url);if(!response.ok)throw Error('原包请求失败（'+response.status+'）。');
 const bytes=new Uint8Array(await response.arrayBuffer());
 const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(v=>v.toString(16).padStart(2,'0')).join('');
 if(sha!==r.asset_sha256)throw Error('原包校验不通过，请刷新后重试。');
 let sum=bytes.length;for(const b of zipCache.values())sum+=b.length;
 if(sum>64*1048576)zipCache.clear();zipCache.set(sha,bytes);return bytes;
}
async function memberBytes(r,path){
 const info=r.members?.find(m=>m.path===path);if(!info)throw Error('未找到原始文件。');
 if(info.size>50*1048576)throw Error('此文件超过 50 MB，请下载完整 ZIP。');
 const data=fflate.unzipSync(await zipBytes(r),{filter:m=>m.name===path});
 if(!Object.prototype.hasOwnProperty.call(data,path))throw Error('原包中未找到此路径。');
 if(data[path].length!==info.size)throw Error('原始文件大小校验失败。');return data[path];
}
function decodeOriginal(bytes){
 if(bytes[0]===255&&bytes[1]===254)return new TextDecoder('utf-16le').decode(bytes);
 if(bytes[0]===254&&bytes[1]===255)return new TextDecoder('utf-16be').decode(bytes);
 try{return new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{return new TextDecoder('gb18030').decode(bytes)}
}
function downloadBytes(bytes,name){const url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function runDownload(button,r,path){const text=button.innerHTML;button.disabled=true;button.textContent='正在准备…';try{downloadBytes(path?await memberBytes(r,path):await zipBytes(r),path?path.split('/').pop():r.file)}catch(e){feedback(e.message)}finally{button.innerHTML=text;button.disabled=false}}
function readerPage(r,path){const size=r.members?.find(m=>m.path===path)?.size;const dirs=new Map();for(const p of r.paths){const dir=p.includes('/')?p.slice(0,p.lastIndexOf('/'))+'/':'';if(!dirs.has(dir))dirs.set(dir,[]);dirs.get(dir).push(p)}const group=([dir,paths])=>`${dir?`<span class="file-folder">${esc(dir)}</span>`:''}${paths.map(p=>`<a class="tree-file ${p===path?'active':''}" href="${fileHref(r,p)}" title="${esc(p)}">${icon('file-text')}<span>${esc(p.split('/').pop())}</span></a>`).join('')}`;const s=r.skills.find(s=>s.path===path);return `<header class="reader-head"><a class="reader-back" href="${pkgHref(r)}">${icon('chevron-left')}${esc(title(r))}</a><code class="reader-path">${esc(path)}</code><span class="small reader-size">${size===undefined?'':bytesLabel(size)}</span><div class="reader-actions"><div class="mode-toggle" role="group" aria-label="显示方式"><button data-mode="formatted" class="active">排版</button><button data-mode="source">源码</button></div><button class="btn" id="downloadFile">${icon('download')}下载此文件</button><button class="btn primary" data-zip="${r.id}">下载完整包</button></div></header><div class="reader-layout"><nav class="file-tree" aria-label="包内文件"><p class="small">${r.paths.length} 个文件</p><input id="fileFilter" aria-label="搜索包内文件" placeholder="搜索文件名"><div id="treeFiles">${[...dirs].map(group).join('')}</div></nav><div class="mobile-file-select"><label for="fileSelect">选择文件</label><select id="fileSelect">${r.paths.map(p=>`<option value="${esc(p)}" ${p===path?'selected':''}>${esc(p)}</option>`).join('')}</select></div><article class="reader-content">${s?.description_zh?`<div class="reader-guide"><strong>中文导读</strong><p>${esc(s.description_zh)}</p></div>`:''}<p id="readerStatus" class="small" role="status">正在读取完整原文…</p><div id="formattedText" class="markdown"></div><pre id="sourceText" hidden></pre><p class="reader-copyright">原文版权归原作者 · ${esc(license(r))}</p></article></div>`}
function sanitizeMarkdown(html){const t=document.createElement('template');t.innerHTML=html;t.content.querySelectorAll('script,style,iframe,object,embed,form,input,button,svg,math,link,meta,base,audio,video,img').forEach(n=>n.remove());for(const n of t.content.querySelectorAll('*')){for(const a of [...n.attributes]){if(!['href','title','colspan','rowspan'].includes(a.name))n.removeAttribute(a.name)}if(n.tagName==='A'){const href=n.getAttribute('href')||'';if(!safeUrl(href)&&!href.startsWith('#'))n.removeAttribute('href');else{n.setAttribute('target','_blank');n.setAttribute('rel','noopener noreferrer')}}}return t.innerHTML}
function formattedMarkdown(text){let body=text,meta='';if(text.startsWith('---\n')||text.startsWith('---\r\n')){const m=text.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);if(m){const rows=m[1].split('\n').filter(x=>/^(name|description):/.test(x));meta='<div class="frontmatter">'+rows.map(line=>{const k=line.slice(0,line.indexOf(':')),v=line.slice(line.indexOf(':')+1).trim().replace(/^['"]|['"]$/g,'');return `<div><span>${k==='name'?'名称':'用途原文'}</span><p>${esc(v)}</p></div>`}).join('')+'</div>';body=text.slice(m[0].length)}}return meta+sanitizeMarkdown(marked.parse(body,{gfm:true,breaks:false}))}
function updateReader(){if(!$('sourceText'))return;const md=/\.(md|markdown|rst)$/i.test(viewFile);const formatted=readerFormat==='formatted'&&md;$('sourceText').textContent=viewText;$('sourceText').hidden=formatted;$('formattedText').hidden=!formatted;if(formatted)$('formattedText').innerHTML=formattedMarkdown(viewText);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===readerFormat));}
async function readCurrentFile(r,path,routeId){const v=++viewVersion;viewRecord=r;viewFile=path;viewText='';viewBytes=null;readerFormat='formatted';$('downloadFile').disabled=true;try{const info=r.members?.find(m=>m.path===path);if(!info)throw Error('包内没有这个文件');if(info.size>5*1048576){$('readerStatus').textContent='此文件大于 5 MB，请下载原文件阅读。';$('downloadFile').disabled=false;return}const bytes=await memberBytes(r,path);if(v!==viewVersion||routeId!==routeVersion)return;viewBytes=bytes;const text=decodeOriginal(bytes);const isText=TEXT_EXT.test(path)||(!bytes.subarray(0,4096).includes(0)&&!/[\u0000-\u0008]/.test(text.slice(0,4096)));$('downloadFile').disabled=false;if(!isText){$('readerStatus').textContent='二进制文件 · '+bytesLabel(bytes.length)+' · 可下载原文件';return}viewText=text;$('readerStatus').textContent='完整原文 · '+text.split('\n').length+' 行 · '+bytesLabel(bytes.length)+(/\.(html|svg)$/i.test(path)?' · 仅以纯文本显示':'');updateReader()}catch(e){if(v===viewVersion&&routeId===routeVersion)$('readerStatus').textContent='读取失败：'+e.message}}
function bindReader(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{readerFormat=b.dataset.mode;updateReader()});$('downloadFile').onclick=()=>viewBytes?downloadBytes(viewBytes,viewFile.split('/').pop()):runDownload($('downloadFile'),selected,viewFile);$('fileSelect').onchange=()=>location.hash=fileHref(selected,$('fileSelect').value);$('fileFilter').oninput=()=>{const q=$('fileFilter').value.toLowerCase();document.querySelectorAll('.tree-file').forEach(a=>a.hidden=!a.title.toLowerCase().includes(q));document.querySelectorAll('.file-folder').forEach(n=>n.hidden=!!q)}}
