// Editorial guidance lives separately from original archives and source text.
const GUIDE_PROFILES=[
 [/月结|对账|收付款/,['指定账户、日期范围和币种，准备账单或交易明细','按原说明先提取或导入数据，再核对余额和金额，最后分析差异','带来源的交易汇总、差异清单或支出分析','分析 2026 年 9 月的交易，按类别和对手方汇总，列出金额最大的 10 项，保留币种和原始来源']],
 [/财务模型|估值|投资/,['准备公司名称、财报期间、金额单位和建模假设；如有模板，一并提供','先确认数据来源和计算口径，再填模型或分析，最后核对关键公式','模型文件、估值结果或有依据的研究结论','按我提供的资料分析，不自行补造数字；列出假设、公式、数据来源和仍待确认的内容']],
 [/数据库与SQL|数据工程|数据治理/,['准备数据库类型、表结构、业务问题和字段说明；先使用只读连接或脱敏样例','先看数据结构和字段含义，再写查询或处理方案，最后对照样例核验结果','查询语句、数据处理方案、质量报告或字段解释','先解释表和字段，再给出解决这个问题的 SQL；说明过滤条件、关联键和结果粒度，先不要写入数据库']],
 [/分析与展示|模型与质量/,['准备 Excel、CSV 或已有查询结果，说明指标含义、时间范围和你想回答的问题','先检查数据是否完整，再分析和展示，最后核对图表与明细金额','分析表、图表、统计结果或检查清单','请解释数据中的变化，给出关键数字、图表和可追溯的计算过程；结论用中文说明']],
 [/文档与写作|知识与资料|研究与学习/,['准备原文、文件或资料链接，说明给谁看、想解决什么问题、输出格式和长度','先读取资料并保留来源，再整理或写作，最后核对引用与遗漏','文档、摘要、资料目录、学习方案或研究报告','先通读我提供的资料，用通俗中文说明重点，标明出处，分清原文事实和你的建议']],
 [/图像与视觉|视频与音频|产品与体验/,['准备素材和参考，说明受众、用途、尺寸、风格、语言和交付格式','先确认方案，再处理素材或制作，最后检查成品尺寸、文字和效果','设计方案、素材文件、页面或视频音频成果','面向中国用户制作，文字用简体中文，保留指定品牌与素材；先给我一个可检查的样例']],
 [/广告与增长|内容与电商|客户与销售/,['准备产品信息、目标客户、渠道、时间范围和预算；如需平台数据，连接对应账号','先确认受众和业务目标，再分析或起草内容，最后检查事实、预算和下一步','客户分析、营销方案、文案或业务数据汇总','面向中国用户，使用自然的简体中文；说明目标人群、执行步骤和衡量效果的方法，先提供草稿']],
 [/应用开发|代码质量|版本与协作开发|需求与架构/,['准备项目代码或仓库、运行环境、目标需求和复现步骤；修改前保留版本','先看项目现状和限制，再实现或排查，最后运行合适的验证','代码修改、测试结果、排查说明或技术方案','先读取相关代码，解释实现方案，再完成这个需求；改完列出变化、运行方法和验证结果']],
 [/云与基础设施|监控与运维|安全检查/,['准备系统或云平台名称、资源范围、相关配置和日志；核对所需权限','先只读检查状态，再提出处理步骤，最后检查结果与影响范围','诊断报告、配置建议、操作方案或状态检查','先只读排查这个问题，指出证据与原因；需要改变配置时先说明影响和恢复方法']],
 [/邮件与会议|任务与协作/,['准备主题、参与人或任务范围、截止时间和期望产出；如需读取服务数据，连接对应账号','先核对信息，再整理任务或起草内容，最后由你核对收件人、日期和行动项','邮件草稿、会议纪要、任务列表或项目安排','请用中文整理背景、结论、负责人和截止时间；不确定的信息标出来，先给我可审核的草稿']],
 [/助手配置与skill|智能体与工作流|记忆与上下文/,['准备使用的 AI 工具、希望它完成的任务、可用资料和现有配置','先核对工具是否支持这个包，再按原说明配置，最后用一个小任务检查效果','助手配置、流程方案、上下文资料或验证结果','先检查这个包适合我使用的 AI 工具吗，再告诉我需要准备什么，并用一个小例子验证']],
 [/法律与公共事务|行业业务|专项工作/,['准备具体业务问题、相关地区、日期、原始材料和适用范围','先确认术语与适用范围，再按原说明分析，最后逐项核对来源和待确认内容','有来源的分析、资料整理或专业工作草稿','用中文解释我提供的材料，标明适用地区与日期，不把没有证据的推断写成事实']],
 [/生活与个人事务/,['说明你的目标、时间、地点、约束条件和已有资料','先明确需求，再按原说明组织方案，最后检查你是否能够实际执行','个人计划、资料查询或事项安排','按我的时间和条件给出可执行的中文步骤，列出需要我补充的信息']],
 [/./,['准备任务目标、输入材料、使用环境和期望结果','先阅读包内说明确认用途，再补齐条件，最后用一个小任务验证','以该skill 原文声明的产出为准','先解释这个skill能做什么、不能做什么，再问我缺少哪些资料；不要假设已经安装或连接服务']]
];
const SKILL_GUIDES={
 'analyze-spending':{title:'看钱花在哪里',purpose:'对已经转换好的银行账单做支出分析：按类别和商家汇总、列出主要收款方，并查看每月变化。',prepare:['已转换的账单数据；这个skill不负责第一次把 PDF 转成交易数据','要分析的账户和日期范围；也可指定产品、账单内容标识或筛选条件'],steps:['先找到你指定范围内的账单；若尚未分类，先做交易分类（categorize_statement）。','分别按类别和商家／交易对手汇总（group_by）。','列出金额最大的商家或交易对手（top_n）。','按月份展示变化（time_series），每个数字或表格行保留账单来源标识 content_hash。'],output:'支出分类合计、商家或交易对手合计、主要商家排名、月度趋势；每行结果可追溯到原账单。',boundary:'不用于首次 PDF 转换、跨期间对账或基准评分。中国银行账单、中文商户名和人民币支持情况，原文没有作出保证，先用一份样本检查。',prompt:'请使用 analyze-spending 分析我已经转换好的账单。账户：[账户]；期间：[开始日期] 至 [结束日期]。先对未分类交易做分类，再给出类别合计、商家／交易对手合计、主要商家排名和月度趋势。用中文解释结果，并在每个数字或表格行保留 content_hash。'},
 '3-statement-model':{title:'把利润表、资产负债表和现金流量表连起来',purpose:'补全已有的三表财务模型模板，把三张表的公式和数据连起来。',prepare:['已有 Excel 三表模板或部分完成的模型','历史数据、预测假设、期间、币种与单位；明确哪些内容是输入，哪些应当用公式计算'],steps:['让助手先检查模型模板和输入区，指出缺失的数据或假设。','在既有模板内补全公式，确认三张表的勾稽关系。','按原说明检查资产负债表平衡、现金余额和公式错误，再核对成品。'],output:'补全后的三表模型及关键核对结果。具体操作依赖包内声明的 Excel 或 Python 环境。',boundary:'这个skill主要补全现有模板。会计口径、期间、单位及假设需要你确认；中文化不会自动改变原模型规则。',prompt:'请使用 3-statement-model 补全我提供的 Excel 三表模板。先列出缺少的数据和假设，确认期间、币种和单位，再补公式。检查资产负债表平衡、现金勾稽和公式错误，用中文解释改了什么。'}
};
function guideProfile(r){return GUIDE_PROFILES.find(([p])=>p.test(r.scene||''))[1]}
function guideData(r,s){
 const specific=s&&((r.id===193&&SKILL_GUIDES[s.name])||(r.id===1002&&s.name==='3-statement-model'))&&SKILL_GUIDES[s.name];if(specific)return {...specific,basis:'按该skill 原文整理',specific:true};
 if(r.id===193&&!s)return {title:'银行账单：先转表格，再分析和对账',purpose:r.summary_zh,prepare:['准备 PDF 账单或已转换数据，明确账户、期间和导出格式'],steps:['第一次处理 PDF：选 convert-statement，把账单转换并核对账户、期间、余额、笔数。','想看钱花在哪里：选 analyze-spending，分析已转换账单的分类、商家和月度趋势。','想查缺月或余额断点：选 reconcile-statements。','想先试效果：选 benchmark-accuracy，使用官方公开样例。'],output:'根据所选任务得到表格导出、支出分析、对账报告或样例准确度评分。',boundary:'连接和真实用量由 Bankstatemently 平台提供；网站只提供说明与原包。',prompt:'我想处理银行账单，使用的 AI 工具是：[名称]。请先读取 Bankstatemently 的 README 和 SETUP.md，检查连接条件，再根据我的目标：[转表格／看支出／对账／试样例] 选择skill。先用官方公开样例验证，不要直接上传我的真实账单。',basis:'按本包 README、SETUP.md 和四条 skill 原文整理',specific:true};
 const p=guideProfile(r),tasks=[...new Set((r.taxons||[]).map(t=>t[2]))].slice(0,5);
 return {title:s?s.name+' · 使用导读':'从这里开始使用',purpose:s?'当前选择的skill：'+s.name+'。这个包的主要用途：'+r.summary_zh+'。这条 skill的具体范围请结合下方原始用途说明确认。':r.summary_zh,prepare:[p[0]],steps:[p[1]],output:p[2],boundary:'这是按工作场景整理的起步建议，具体支持范围以所选skill 原文为准。',prompt:`请${s?'使用 '+s.name:'先查看 '+r._title+' 包内的说明'}，帮助我完成：[填写具体任务]。\n我的材料：[文件或资料]；使用环境：[AI 工具／平台]；期望输出：[格式]。\n${p[3]}。\n先按原说明检查是否适用和缺少什么条件；不要假设已经安装、登录或连接服务。`,basis:'按目录用途和工作场景整理；不是原文逐字翻译',tasks};
}
function guideContent(r,s){const g=guideData(r,s),mcp=(r.mcp_servers||[]).length;
 return `<div class="cn-guide"><div class="guide-intro"><span class="guide-label">中文使用指南</span><h3>${esc(g.title)}</h3><p>${esc(g.purpose)}</p><small>${esc(g.basis)} · 原文件完整保留</small></div>
 ${reuseContent(r,s,true)}
 <div class="guide-section"><h3>② 先准备什么？</h3><ul>${g.prepare.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></div>
 <div class="guide-section"><h3>③ 第一次怎么开始？</h3><ol><li>到“文件与下载”下载完整 ZIP 并解压，保留文件夹结构；只下载一份 SKILL.md，可能会漏掉脚本和参考资料。</li><li>把解压后的资料交给你使用的 AI 工具，让它先读取 README、插件配置和所选 SKILL.md，按原说明判断安装／加载方式。不要把 Claude 的安装方式直接套到其他工具。</li><li>按助手列出的条件完成依赖、账号或服务连接，再给它一份小样本开始任务。</li>${g.steps.map(p=>`<li>${esc(p)}</li>`).join('')}</ol><details><summary>不知道怎么安装？复制这段话给 AI 助手</summary><pre class="prompt-text">我下载了 ${esc(r._title)} 的完整包，使用的 AI 工具是：[填写名称]。请先读取 README、插件配置和 SKILL.md，判断是否兼容；列出准确的加载步骤、依赖和服务账号要求。没有明确说明的地方先告诉我，不要猜安装命令。</pre></details></div>
 ${r.id===193?`<details class="guide-section"><summary>Bankstatemently 的具体连接方法（来自本包 README）</summary><p>如果使用 Claude Code，可按本包 README 的插件市场方式输入下面两条命令，然后启用插件。首次调用工具时会打开浏览器登录。</p><pre class="prompt-text">/plugin marketplace add bankstatemently/plugins
/plugin install bankstatemently@bankstatemently</pre><p>也可以只连接 MCP 服务：</p><pre class="prompt-text">claude mcp add --transport http bankstatemently https://api.bankstatemently.com/mcp</pre><p>如果使用其他 AI 工具，先确认它支持该 HTTP MCP 服务及浏览器登录，按照该工具的连接入口配置；不要直接照抄 Claude 命令。连接后让助手调用 get_credits 确认连接和可用额度。</p><p>处理账单会将文件交给 Bankstatemently 服务。先用 README 给出的公开样例测试：
https://bankstatemently.com/benchmark/statements/bsb-004-statement.pdf</p><p>本包版本 0.15.4 的说明记载转换和首次分类会消耗额度，公开基准转换不消耗额度；实际收费与可用性以平台当前规则为准。</p></details>`:''}
 <div class="guide-section"><h3>④ 可以直接这样问</h3><p>把方括号换成自己的信息，再发给已加载该skill的 AI 助手。</p><pre class="prompt-text">${esc(g.prompt)}</pre><button class="copy-prompt" data-copy-prompt="${esc(g.prompt)}">复制中文问法</button><span class="copy-result" role="status"></span></div>
 <div class="guide-section"><h3>⑤ 做完看什么？</h3><p>${esc(g.output)}</p><p>先核对输入范围和结果样例，再决定是否用于完整任务。${esc(g.boundary)}</p></div>
 <details class="guide-section"><summary>国内使用时，需要额外确认什么？</summary><ul><li>界面和提问可以用简体中文，原始英文skill名、字段名、命令和文件路径应当保留，方便助手找到资料。</li><li>如果要处理中文文件名、人民币、国内日期或会计口径，先用小样本检查；明确币种和单位，不能把美元数值直接改成“元”。</li><li>如果包连接的是特定外部平台，中文指南不会把它变成微信、钉钉、飞书或 WPS 插件；核对原平台账号、地区、网络可用性与费用。</li></ul></details>
 <details class="guide-section"><summary>查看包内已识别的环境要求</summary><ul>${(r.requirements||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>
 ${s?`<p class="small">对应原文件：<code>${esc(s.path)}</code></p><details><summary>作者的原始用途说明</summary><p>${esc(s.description||'原文未提供 description')}</p></details>`:''}</div>`}
function guideOverview(r){return guideContent(r,null)+`<h3>接下来选一条 skill</h3><p class="small">每条 skill可查看中文导读、完整原文或下载原文件。</p>`+(r.skills||[]).map(s=>`<div class="guide-skill"><b>${esc(SKILL_GUIDES[s.name]?.title||s.name)}</b><code>${esc(s.path)}</code><button data-guide="${esc(s.path)}">中文怎么用</button><button data-read="${esc(s.path)}">查看原始文件 ↗</button></div>`).join('')}
async function copyGuidePrompt(button){try{await navigator.clipboard.writeText(button.dataset.copyPrompt);button.nextElementSibling.textContent='已复制，可粘贴给 AI 助手'}catch{button.nextElementSibling.textContent='请选中上方文字复制'}}
function bindGuideButtons(root){root.querySelectorAll('[data-copy-prompt]').forEach(b=>b.onclick=()=>copyGuidePrompt(b));root.querySelectorAll('[data-guide]').forEach(b=>b.onclick=async()=>{await openOriginal(selected,b.dataset.guide);setViewerMode('guide')})}

Object.assign(SKILL_GUIDES,{"convert-statement": {"title": "把银行 PDF 账单变成 Excel 或 CSV", "purpose": "提取 PDF 银行账单中的账户、期间、余额和交易，并按需要导出表格。", "prepare": ["一份 PDF 账单：文件附件、本地文件或公开 HTTPS 链接", "需要的导出格式，例如 Excel（XLSX）或 CSV；先确认 Bankstatemently 服务已连接"], "steps": ["附件或公开 PDF 链接交给 convert_statement；本地文件不能直接传递时，先 request_upload 再上传并转换。", "若仍在处理，查询 get_statement，直到完成或返回终止结果。", "核对账户、期间、余额和交易笔数，再选择导出格式。", "通过 get_statement 获取需要的 CSV、XLSX、QBO 或 Xero 导出链接。"], "output": "转换摘要、账户信息、账单期间、余额、交易笔数和可选导出下载链接。", "boundary": "这是转换skill；支出分析、跨期间对账和基准评分分别使用其他skill。数据通过外部服务处理，先用公开样例确认效果和用量。", "prompt": "请使用 convert-statement 转换这份银行 PDF 账单：[附件或链接]。先显示账户、期间、期初期末余额和交易笔数，核对后导出为 Excel（XLSX）。金额和币种保留原样，不把无法识别的内容编造成交易。"}, "reconcile-statements": {"title": "检查有没有缺月份、余额能否接上", "purpose": "检查一组已经转换好的账单，找出缺失期间、重叠期间、余额不连续和跨账户转账问题。", "prepare": ["已经转换好的多份账单", "账户、产品、日期范围或筛选条件"], "steps": ["用 list_statements 找范围内的账单，再用 get_statement 取得已完成账单。", "按账户和期间排序，查缺失、重叠和空档。", "把每期的期末余额与下一期的期初余额比较；发现断点时保留两份账单的 content_hash。", "需要时用 list_transfers 查看跨账户匹配和大额未匹配流动，最后整理对账报告。"], "output": "覆盖期间、缺失期间、余额断点和转账核对结果，保留来源账单标识。", "boundary": "不是把新 PDF 转成数据的skill，也不是支出分类或基准评分。", "prompt": "请使用 reconcile-statements 核对账户：[账户]，期间：[开始日期] 至 [结束日期]。检查缺失和重叠期间、期初期末余额是否连续，以及跨账户转账；每个余额断点保留两份来源账单的 content_hash，用中文说明。"}, "benchmark-accuracy": {"title": "用官方样例检查提取准不准", "purpose": "转换并评分 Bankstatemently 已公开的基准账单，把提取结果与已知正确数据比较。", "prepare": ["官方基准账单编号或 PDF 链接，例如 bsb-004", "已连接 Bankstatemently 服务"], "steps": ["读取基准目录，选择指定的已发布样例。", "用 convert_statement 转换，再通过 get_statement 取得原始数据模式的结果。", "把样例编号和原始解析交易交给 evaluate_benchmark。", "展示提取准确度、完整性分数、总分和主要错误类别，保留样例编号及 content_hash。"], "output": "基准样例的提取准确度、完整性分数、总分和主要错误类别。", "boundary": "只用于已发布的官方基准样例；不能把自己的普通账单直接当成有标准答案的基准来评分。", "prompt": "请使用 benchmark-accuracy 转换并评分官方 bsb-004 基准样例。显示提取准确度、完整性分数、总分和主要错误类别，保留样例编号与 content_hash，用中文解释。"}});

function reuseAssessment(r){const e=r.reuse||{};return r.id===193?'依赖 Bankstatemently 服务；可改写工作流程':r.id===1002?'有本地 Python 复用路径，需验证':e.remote?.length?'包含外部服务连接，复用时需准备或替换服务':e.local?.length?'包含本地 MCP 启动配置，需准备运行环境':e.scripts?.length?'包含代码文件，可检查是否适合独立复用':'可参考skill 和资料；运行依赖还需核对'}
function reuseContent(r,s,compact=false){
 const e=r.reuse||{},list=(xs)=>xs.length?`<ul>${xs.slice(0,12).map(x=>`<li><code>${esc(x)}</code></li>`).join('')}</ul>${xs.length>12?`<p>另有 ${xs.length-12} 个文件，请在“文件与下载”查看完整清单。</p>`:''}`:'<p>未检出这类文件。</p>',licenses=[...new Set((r.plugins||[]).map(x=>x.license).filter(Boolean))];
 const prompt=`我想复用 ${r._title||r.file}${s?' 中的 '+s.name:''}，原产品可能无法使用。我的 AI 工具：[名称]；可用环境：[例如 Python／Excel／SQL]；输入：[文件或脱敏样例]。请先读取原包的 README、许可证、所选 SKILL.md、MCP 配置及关联脚本。分清工作方法、实际代码和外部服务；逐项列出依赖与替代方案，不把连接配置当成服务源码。保持原文件不变，在新目录做中文适配，保留原输入输出规则、引用来源和核对条件。先用小样本验证，说明哪些已验证、哪些还不能运行。许可不清楚时先标明。`;
 let route=r.id===193?`<p><b>能拿走：</b>4 条 skill与命令中的账单转换、支出分析、对账和基准检查流程。</p><p><b>拿不走：</b>这个包只有服务连接与说明，没有 PDF 解析、交易存储或分类的后端程序。原服务不能使用时，原工具调用也不能直接执行。</p><ol><li>先复用支出分析：准备已整理好的 Excel／CSV 交易表，明确日期、金额、币种、商家和类别。</li><li>把 categorize_statement、group_by、top_n、time_series 分别替换成自己的分类规则、Python／SQL 汇总、排名和月度统计。</li><li>保留来源标识 content_hash，或设计可追溯的账单／行标识；核对分类合计与原交易总额。</li><li>PDF 转换需要另找解析工具并核对余额、金额和笔数；对账需另实现期间、余额连续与转账检查；基准评分需要有标准答案的样例。</li></ol><p>这是一条改写路线，本网站没有提供或验证替代后端。</p>`:r.id===1002?`<p><b>能拿走：</b>财务模型的工作说明、公式与格式参考，以及 DCF 检查脚本。包内 xlsx-author 描述了无 Office 时使用 Python／openpyxl 生成 Excel 的路线。</p><ol><li>保留所选 SKILL.md 及其 references、scripts 和依赖文件，先读 agents/model-builder.md 与 xlsx-author 的说明。</li><li>若原 Office 工具不能使用，可按包内 Python 路线另写 Excel 生成脚本；保留公式、输入区标识和三表平衡检查。</li><li>DCF 检查脚本位于 skills/dcf-model/scripts/validate_dcf.py；先读它要求的工作表、单元格和依赖，再用样本验证。</li><li>国内使用时明确会计口径、人民币单位、期间与财报来源。公式缓存为空时，不能把空值当成检查通过。</li></ol><p>这是源码与说明中可见的复用路径，相关脚本尚未在本网站运行验收；本包未检出许可证声明，不能据此认定可任意再发布。</p>`:`<ol><li>先挑一条 skill，把 SKILL.md 与它引用的脚本、参考资料和模板一起保留，查看原许可证。</li><li>让 AI 列出原文里的工具调用、账号、软件和输入要求。纯工作步骤可作为新skill的参考；工具名称本身不能替代实际能力。</li><li>原产品不能用时，为每个调用找到实际替代能力，例如文件读取、数据库查询或文档生成；在新目录改写适配，保留原规则和来源。</li><li>用一份小样本核对输入、输出和错误处理，再扩大使用范围。有代码文件不代表已验证能独立运行。</li></ol>`;
 const evidence=`<p>扫描到 ${(e.configs||[]).length} 份 MCP 配置、${(e.scripts||[]).length} 个代码文件、${(e.references||[]).length} 个参考／模板文件。代码数量不等于产品后端数量。</p>${(e.remote||[]).map(x=>`<p>外部连接：<b>${esc(x.name)}</b> · <code>${esc(x.endpoint)}</code><br>依据：<code>${esc(x.path)}</code>。需要对应服务；账号、费用与可用性需自行确认。</p>`).join('')}${(e.local||[]).map(x=>`<p>本地 MCP 启动线索：${esc(x.name)} · <code>${esc(x.path)}</code>。需阅读实际命令与环境要求。</p>`).join('')}${!(e.configs||[]).length?'<p>未检出 MCP 配置，不代表没有产品依赖：skill 原文仍可能调用宿主工具或要求特定软件。</p>':''}${(e.unknown||[]).length?'<p>部分配置无法完整判定，请阅读原配置；这里不猜连接方式。</p>':''}`;
 return `<${compact?'details':'section'} class="guide-section reuse-guide">${compact?'<summary>原产品用不了，还能复用吗？</summary>':'<h3>原产品用不了，还能复用吗？</h3>'}<p class="reuse-verdict"><b>${esc(reuseAssessment(r))}</b></p><p>插件是装资料与连接配置的包。里面可以有skill、MCP 连接、脚本和模板，但不一定包含原产品本身。SKILL.md 说明怎么做事，MCP 配置说明连接什么；是否有可运行的程序，要看实际代码和依赖。</p>${route}<details><summary>查看这次判断的文件依据</summary>${evidence}<h4>代码文件</h4>${list(e.scripts||[])}<h4>参考与模板</h4>${list(e.references||[])}<h4>依赖文件</h4>${list(e.dependencies||[])}<p>插件声明的许可：${esc(licenses.join('、')||'未声明')}。${(e.licenses||[]).length?'另有许可文件：':'未检出 LICENSE／COPYING 文件。'} ${(e.licenses||[]).map(x=>`<code>${esc(x)}</code>`).join('、')} 复用与再分发前按原许可核对，保留作者和声明。</p></details><h4>复制给 AI，让它帮你改成可复用版本</h4><pre class="prompt-text">${esc(prompt)}</pre><button class="copy-prompt" data-copy-prompt="${esc(prompt)}">复制复用需求</button><span class="copy-result" role="status"></span><p class="small">判断来自包内文件的静态阅读，未验证服务当前可用性或脚本运行效果。中文说明独立保存，原文件保持原样。</p></${compact?'details':'section'}>`;
}
